services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: primepass_db
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: primepass_backend
    restart: always
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: primepass_db
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./frontend
    container_name: primepass_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mariadb_data:
