apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: primepass-backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: primepass-primary
            - name: DB_NAME
              value: primepass_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: primepass-appuser
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: primepass-appuser
                  key: password